version: '3'
services:
  postgres:
    image: "postgres"
    container_name: "budget-psql"
    ports:
      - 54320:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/tmp:/tmp2
    environment:
      - POSTGRES_DB=budget
      - POSTGRES_USER=budget
      - POSTGRES_PASSWORD=budget
